<?php
function movie_theme($existing, $type, $theme, $path)
{
  return array(
    'start_movie_reservation' => array(
      'variables' => array(
        'genres' => array(),
        'movies' => array()
      )
    ),
    'create_table_reservations' => array(
      'variables' => array(
        'msg' => ''
      )
    ),
    'process_xml_new_books' => array(
      'variables' => array(
        'books' => array()
      )
    ),
    'save_reservation' => array(
      'variables' => array(
        'msg' => ''
      )
    ),
    'create_table_subscriptions' => array(
      'variables' => array(
        'msg' => ''
      )
    ),
    'save_subscription' => array(
      'variables' => array(
        'msg' => ''
      )
    ),
  );
}
